### ISSUE TITLE
Events do not register when compiled with RequireJS

### ISSUE THREAD

**Issue by scotthovestadt** [patricklodder/jquery-zclip#1] opened 2013-03-12 19:20 UTC
The Flash movie is dependent on global var "ZeroClipboard". However, this var is renamed and placed in a closure when minified with RequireJS.

This can be fixed simply by changing "var ZeroClipboard" to "ZeroClipboard".

**Comment by patricklodder** [comment] 2013-03-12 23:47
#2 is a duplicate of this, but closing this one as the other is a pull request.

**Closed as completed by patricklodder** 2013-03-12 23:47 UTC
Labels: duplicate
